var signo = prompt('¿Cual es tu signo?')


switch (signo) {
  case 'aries':
    console.log('La tensión en el trabajo irá en aumento hasta finalizar el mes, por lo que la convivencia en el trabajo será complicada, es ahí donde Aries deberá hacer uso de sus habilidades y actuar con destreza para encontrar el camino hacia el éxito. Aunque hoy será un día cansado, los nacidos bajo este signo del Zodiaco tendrán la energía para quedar con los amigos, una copita reavivará el alma para soportar la semana. Con la alineación de los astros, Aries tendrá un mes ideal para cerrar ciclos sentimentales, esto permitirá que entren nuevas ilusiones en un momento importante para que Aries inicie una etapa de renacer emocional, aunque el amor no surgirá a primera vista, será un paso importante para dejar enamorarse, si tiene pareja, llegará una sorpresa muy grata para la relación. A pesar de tener buena salud, Aries deberá empezar a cuidar su alimentación antes de que llegue alguna sorpresa de colesterol.')
    break
  case 'tauro':
    console.log('Hoy, Tauro recibirá un dinero que ya daba por perdido, y que le vendrá muy bien para emprender en los proyectos que tiene en mente, será conveniente que Tauro mantenga, este mes, bien enfocados sus objetivos ya que las expectativas de éxito serán altas. En la última semana de marzo, la posición de los astros creará una energía que será positiva si los nacidos bajo este signo del Zodiaco mantienen ese buen humor que les caracteriza, con ello, se potenciarán los encantos innatos de Tauro despertando cierta atracción que le devolverá la ilusión en el amor, aunque ser cauteloso con sus sentimientos será ideal para no decepcionarse, si tiene pareja, a pesar de las discusiones y discrepancias, Tauro tendrá una época de romanticismo con su pareja. Está primavera será crucial que Tauro se cuide para evitar catarros, los cambios de temperatura podrían afectar su salud. ')
    break
  case 'geminis':
  case 'gémenis':
    console.log('Bajo la oscilación de los astros en la última semana de marzo, Géminis empezará a generar un orden en su vida tanto personal, como profesional, esto le dará una nueva perspectiva para enfocarse en proyectos importantes para que Géminis despunte con éxito en su trabajo, esto traerá cambios en su dinero y carrera para este año. En un terreno más íntimo, los nacidos bajo este signo del Zodiaco tomarán hoy decisiones importante que darán un giro positivo a su vida, se avecina una fase de cambios que abrirá a Géminis las puertas del amor si está soltero, si tiene una relación, deberá ser cauto de no caer en tentaciones que afecten el vínculo amoroso, si existen sentimientos verdaderos se fortalecerán como pareja. La vida social tan activa podría afectar la salud de Géminis más de lo que piensa, por ello deberá descansar y evitar los excesos de comida y alcohol. ')
    break
  case 'cancer':
  case 'cáncer':
    console.log('Este mes, la comunicación en el trabajo será clave para que Cáncer mantenga el orden en las negociaciones que deberá cerrar antes de finalizar marzo, esto le dará a Cáncer la confianza para emprender un nuevo camino en su carrera con beneficios significativos en sus finanzas. Los planes con la familia, no será lo que más necesite Cáncer hoy después de un día ajetreado, pero pasar tiempo con ellos, le dará la tranquilidad que busca para reponer fuerzas. Los nacidos bajo este signo del Zodiaco, con ayuda de la energía de los astros, tendrán la posibilidad de fortalecer, este mes los lazos sentimentales con su pareja, si está soltero, se creará una ambiente de seducción con una persona por quien Cáncer se siente algo más que atraído, surgirán sentimientos que harán surgir ese amor que existe entre ambos.  Este mes Cáncer deberá tener cuidado con el catarro podría tener las defensas bajas.')
    break
  case 'leo':
    console.log('Habrá cambios significativos para Leo en el terreno profesional, lo que le motivará a buscar nuevos retos que le permitan progresar en el trabajo, por ello, Leo no deberá descartar que esta última semana de marzo se generen oportunidades en su carrera que le darán el éxito que busca. Las discusiones con el dinero, serán hoy el tema principal en casa, a pesar de estar en una época estable, será conveniente que Leo no derroche más, y aprenda a ahorrar. Las inquietudes de los nacidos bajo este signo del Zodiaco, permitirá que viva este mes grandes aventuras, las cuales aportará una actitud conquistadora que dejará huella en su entorno, tanto que alguien podría caer en sus redes, si tiene una relación, Leo estará en la mejor disposición de volver a conquistar a su pareja, esto hará que el amor entre ambos se fortalezca.  La llegada de la primavera permitirá que la salud de Leo mejore, aun así, deberá seguir con los buenos hábitos.')
    break
  case 'virgo':
    console.log('En estos últimos días marzo, Virgo conocerá a alguien que le ayudará a aterrizar las ideas para empezar a palpar sus objetivos con mayor nitidez, esto le dará la fortaleza para dar el primer paso hacia el cambio que Virgo busca en el trabajo, será un periodo complicado, pero que le llevará al éxito profesional. Aunque el dinero no será un problema para Virgo, tener un orden en sus finanzas, evitará muchas situaciones incómodas en un futuro cercano. Este mes, en el terreno personal podrían surgir ciertas desavenencias con algún familiar que provocará un entorno embarazoso para los que le rodean, el distanciamiento será la mejor opción hasta que se calmen las aguas. El tránsito de los astros para la segunda mitad de marzo, augura un tórrido romance para los nacidos bajo este signo del Zodiaco con una persona cercana, si tiene una relación, el amor podría ser una época de muchos altibajos que Virgo superará con comunicación y sinceridad. Hoy es un día perfecto para salir a despejar la mente, andar en bici, oír música… le servirá a Virgo para aclarar ideas y liberar el estrés acumulado que afecta su salud.')
    break
  case 'libra':
    console.log('Este mes, surgirán muchas ideas y propuestas que si son bien enfocadas permitirán a Libra cerrar marzo con buenas expectativas de éxito, ya que su ambición profesional y económica le hará embarcarse en proyectos de gran magnitud para abrirse camino en nuevos horizontes. Los nacidos bajo este signo del Zodiaco que no les ha sonreído el amor este primer trimestre del año, empezarán a cambiar el rumbo de s vida sentimental, debido a la alineación de los astros, que incitarán para Libra el romance, aunque no surgirá antes de finalizar el mes, habrá gratas sorpresas durante el año, si tiene pareja, es momento de Libra para dar un paso a su relación, o tomar decisiones importantes antes de que la rutina apague la pasión que les une. Los planes de hoy serán diferentes su Libra realiza nuevas actividades que fomenten su salud física y menta')
    break
  case 'escorpio':
    console.log('En el terreno laboral y económico, la última semana de marzo, será clave para que Escorpio escoja un porvenir en su carrera, esto significa que hoy habrá decisiones y cambios que le permitirán tener nuevas perspectivas profesionales, que abrirán camino hacia horizontes en los que Escorpio podrá progresar en su trabajo, por ello, será ideal mantener bien enfocado sus intereses. Planificar algún viaje, para las próximas vacaciones, levantará hoy el ánimo de los nacidos bajo este signo del Zodiaco, lo que necesita para recuperar ese humor que le caracteriza, esta actitud proactiva permitirá que la energía de los astros actúe a favor de Escorpio, lo que beneficiará a los solteros en el amor ya que despertará atracción en alguien que está conociendo y que dará un paso para conquistar, si tiene un pareja, el miedo al compromiso está frenando que su relación avance hacia una nueva etapa sentimental. Camina, bailar, hacer yoga o alguna otra actividad que disfrute ayudará a Escorpio ordenar muchas ideas y equilibrar su salud emocional y mental.')
    break
  case 'sagitario':
    console.log('Se avecina un proyecto muy importante para la carrera de Sagitario, con el cual, tendrá al posibilidad de dar un salto significativo en el trabajo que marcará un antes y un después en su vida en general, aunque todo está a favor de Sagitario, será conveniente actuar con destreza y habilidad para que las expectativas de éxito sigan altas. Hacer planes para las próximas vacaciones será el come cocos de hoy para los nacidos bajo este signo del Zodiaco, tanto que si no queda de acuerdo con los amigos, tomará decisiones, pero ese viaje será necesario realizar para la paz espiritual de Sagitario. El miedo a enamorarse hará que este mes pierda muchas oportunidades de coincidir con alguien que le devolverá las ilusiones, por ello, esta semana de marzo, la posición de los astros  pondrá en su camino a una persona con quien los nacidos bajo este signo del Zodiaco podría conocer el amor si se deja llevar por sus sentimientos y arriesgarse a vivir el presente. Relajarse, hacer deporte al aire libre o actividades, será conveniente que Sagitario empiece a cuidar su salud este mes.')
    break
  case 'capricornio':
    console.log('La última semana de marzo será importante que Capricornio tome algunas decisiones para cerrar el mes con buenas expectativas de progreso en el trabajo, para ello, enfocarse en sus perspectivas laborales encaminaran a Capricornio hacia proyectos expansivos de los cuales podría beneficiarse en sus finanzas.  Los nacidos bajo este signo del Zodiaco experimentarán hoy una sensación de inquietud, que le permitirá indagar en terrenos nuevos que enriquecerán el crecimiento personal de este signo.  Con la llegada de la primavera el movimiento de los astros será crucial para que se generen cambios en la vida sentimental de Capricornio, por ello, no deberá descartar que este mes, el amor estará muy presente, tanto si tiene o no pareja, pero si Capricornio está soltero, este año podría llegar a enamorarse. La actividad al aire libre, será beneficioso para la salud física, mental y emocional de Capricornio, se sentirá renovado en su interior.')
    break
  case 'acuario':
    console.log('Antes de que acabe marzo, surgirán una serie de posibilidad para que Acuario desempeñe alguna idea para fomentar su carrera hacia nuevos horizontes que despierten la motivación que Acuario está perdiendo pro el trabajo, aunque se avecinan cambios profesionales, este mes, cerrará con buenas expectativas para que lleguen pronto.  Los aires primaverales, así como la conjunción de los astros propiciarán una etapa favorable para los nacidos bajo este signo del Zodiaco a nivel personal, hoy será un día en el cual podrá solucionar algunas diferencias con alguien cercano, en el amor, surgirá cierta atracción que podría culminar en un tórrido romance, si tiene pareja, será un periodo ideal para que Acuario dé un paso más en su relación. Para iniciar la semana con energía, será conveniente que Acuario descanse y desconecte de la rutina, será lo más conveniente para su salud física y mental')
    break
  case 'piscis':
    console.log('En estos últimos días de marzo, Piscis empezará a notar que se está cerrando un ciclo que ha marcado su vida profesional, esto abrirá una nueva etapa en su carrera que generará cambios importantes para progresar en el trabajo, será un mes de grandes expectativas de éxito si Piscis deja a un lado el miedo a lo desconocido y asume con ambición los retos. Hoy será un día complicado para quedar con los amigos, o la familia, a pesar de ello, pasar tiempo con los suyos será reconfortante a nivel personal, por ello, será importante encontrarse con ellos. El movimiento de los astros, propiciará un segundo periodo del mes algo tenso a nivel emocional, si los nacidos bajo este signo del Zodiaco no empiezan a mostrar más sus sentimientos, podría provocar un distanciamiento con la pareja, si está soltero, será un periodo de romance, pasión, pero Piscis no encontrará el amor hasta que no deje el pasado atrás, aclarar emociones será clave para dar un paso. A finales de este mes, Piscis estará bajo mucha presión que si no sabe equilibrar le afectará en su salud.')
    break
  default:
    console.log('No es un signo valido')
    break
}
